version: 2
project_name: kumabot

before:
  hooks:
    - go mod tidy

builds:
  - id: kumabot
    main: ./cmd/kumabot
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    skip: true

archives:
  - formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_{{ title .Os }}_{{ .Arch }}"

release:
  mode: replace
  draft: false

dockers_v2:
  - id: kumabot
    dockerfile: Dockerfile
    extra_files:
      - cmd/
      - internal/
      - go.mod
      - go.sum
    images:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}"
      - "docker.io/{{ .Env.DOCKER_USERNAME }}/{{ .ProjectName }}"
    tags:
      - "{{ .Tag }}"
      - "{{ if not .Prerelease }}latest{{ end }}"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
