version: 2
project_name: kumabot

before:
  hooks:
    - go mod tidy

archives:
  - formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_{{ title .Os }}_{{ .Arch }}"

release:
  mode: replace
  draft: false

dockers_v2:
  - id: kumabot-docker
    dockerfile: Dockerfile
    image_templates:
      - "ghcr.io/{{ .Runtime.GitHubOrg }}/{{ .ProjectName }}:{{ .Tag }}"
      - "ghcr.io/{{ .Runtime.GitHubOrg }}/{{ .ProjectName }}:latest"
      - "docker.io/{{ .Env.DOCKER_USERNAME }}/{{ .ProjectName }}:{{ .Tag }}"
      - "docker.io/{{ .Env.DOCKER_USERNAME }}/{{ .ProjectName }}:latest"
    use: buildx
    build_flag_templates:
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
    
    platforms:
      - linux/amd64
      - linux/arm64

    skip_push: "{{ .Prerelease }}"
