version: 2
project_name: kumabot

before:
  hooks:
    - go mod tidy

archives:
  - formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_{{ title .Os }}_{{ .Arch }}"

release:
  mode: replace
  draft: false

dockers_v2:
  - id: kumabot
    dockerfile: Dockerfile
    extra_files:
      - cmd/
      - internal/
      - go.mod
      - go.sum
    images:
      - "ghcr.io/{{ .Runtime.GitHubOrg }}/{{ .ProjectName }}"
      - "docker.io/{{ .Env.DOCKER_USERNAME }}/{{ .ProjectName }}"
    tags:
      # Always create a tag for the version (e.g., v1.0.0 or v1.0.0-rc1)
      - "{{ .Tag }}"
      # Only create the "latest" tag if this is NOT a pre-release
      - "{{ if not .Prerelease }}latest{{ end }}"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
